#!/usr/bin/env bash
set -euo pipefail

# ==== CONFIG (LOCAL / HERD) ====
DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_NAME="property"
DB_USER="root"

START_YEAR=2008
END_YEAR=$(date +%Y)

echo ">>> Upserting epc_staging into epc_certificates year by year (${START_YEAR}..${END_YEAR})"

for Y in $(seq "${START_YEAR}" "${END_YEAR}"); do
  echo ">>> Processing year ${Y}..."
  NEXT_Y=$((Y+1))

  mysql --local-infile=1 -h "${DB_HOST}" -P "${DB_PORT}" -u "${DB_USER}" "${DB_NAME}" <<SQL
INSERT INTO epc_certificates (
  LMK_KEY,
  ADDRESS1, ADDRESS2, ADDRESS3, POSTCODE,
  BUILDING_REFERENCE_NUMBER,
  CURRENT_ENERGY_RATING, POTENTIAL_ENERGY_RATING,
  CURRENT_ENERGY_EFFICIENCY, POTENTIAL_ENERGY_EFFICIENCY,
  PROPERTY_TYPE, BUILT_FORM,
  INSPECTION_DATE,
  LOCAL_AUTHORITY, CONSTITUENCY, COUNTY,
  LODGEMENT_DATE,
  TRANSACTION_TYPE,
  ENVIRONMENT_IMPACT_CURRENT, ENVIRONMENT_IMPACT_POTENTIAL,
  ENERGY_CONSUMPTION_CURRENT, ENERGY_CONSUMPTION_POTENTIAL,
  CO2_EMISSIONS_CURRENT, CO2_EMISS_CURR_PER_FLOOR_AREA, CO2_EMISSIONS_POTENTIAL,
  LIGHTING_COST_CURRENT, LIGHTING_COST_POTENTIAL,
  HEATING_COST_CURRENT, HEATING_COST_POTENTIAL,
  HOT_WATER_COST_CURRENT, HOT_WATER_COST_POTENTIAL,
  TOTAL_FLOOR_AREA,
  ENERGY_TARIFF,
  MAINS_GAS_FLAG,
  FLOOR_LEVEL,
  FLAT_TOP_STOREY,
  FLAT_STOREY_COUNT,
  MAIN_HEATING_CONTROLS,
  MULTI_GLAZE_PROPORTION,
  GLAZED_TYPE,
  GLAZED_AREA,
  EXTENSION_COUNT,
  NUMBER_HABITABLE_ROOMS,
  NUMBER_HEATED_ROOMS,
  LOW_ENERGY_LIGHTING,
  NUMBER_OPEN_FIREPLACES,
  HOTWATER_DESCRIPTION,
  HOT_WATER_ENERGY_EFF,
  HOT_WATER_ENV_EFF,
  FLOOR_DESCRIPTION,
  FLOOR_ENERGY_EFF,
  FLOOR_ENV_EFF,
  WINDOWS_DESCRIPTION,
  WINDOWS_ENERGY_EFF,
  WINDOWS_ENV_EFF,
  WALLS_DESCRIPTION,
  WALLS_ENERGY_EFF,
  WALLS_ENV_EFF,
  SECONDHEAT_DESCRIPTION,
  SHEATING_ENERGY_EFF,
  SHEATING_ENV_EFF,
  ROOF_DESCRIPTION,
  ROOF_ENERGY_EFF,
  ROOF_ENV_EFF,
  MAINHEAT_DESCRIPTION,
  MAINHEAT_ENERGY_EFF,
  MAINHEAT_ENV_EFF,
  MAINHEATCONT_DESCRIPTION,
  MAINHEATC_ENERGY_EFF,
  MAINHEATC_ENV_EFF,
  LIGHTING_DESCRIPTION,
  LIGHTING_ENERGY_EFF,
  LIGHTING_ENV_EFF,
  MAIN_FUEL,
  WIND_TURBINE_COUNT,
  HEAT_LOSS_CORRIDOR,
  UNHEATED_CORRIDOR_LENGTH,
  FLOOR_HEIGHT,
  PHOTO_SUPPLY,
  SOLAR_WATER_HEATING_FLAG,
  MECHANICAL_VENTILATION,
  ADDRESS,
  LOCAL_AUTHORITY_LABEL,
  CONSTITUENCY_LABEL,
  POSTTOWN,
  CONSTRUCTION_AGE_BAND,
  LODGEMENT_DATETIME,
  TENURE,
  FIXED_LIGHTING_OUTLETS_COUNT,
  LOW_ENERGY_FIXED_LIGHT_COUNT,
  UPRN,
  UPRN_SOURCE,
  REPORT_TYPE
)
SELECT
  NULLIF(s.LMK_KEY,''),

  NULLIF(s.ADDRESS1,''),
  NULLIF(s.ADDRESS2,''),
  NULLIF(s.ADDRESS3,''),
  NULLIF(s.POSTCODE,''),

  NULLIF(s.BUILDING_REFERENCE_NUMBER,''),

  NULLIF(s.CURRENT_ENERGY_RATING,''),
  NULLIF(s.POTENTIAL_ENERGY_RATING,''),

  CASE WHEN NULLIF(s.CURRENT_ENERGY_EFFICIENCY,'') REGEXP '^[0-9]+$' THEN s.CURRENT_ENERGY_EFFICIENCY+0 ELSE NULL END,
  CASE WHEN NULLIF(s.POTENTIAL_ENERGY_EFFICIENCY,'') REGEXP '^[0-9]+$' THEN s.POTENTIAL_ENERGY_EFFICIENCY+0 ELSE NULL END,

  NULLIF(s.PROPERTY_TYPE,''),
  NULLIF(s.BUILT_FORM,''),

  STR_TO_DATE(NULLIF(s.INSPECTION_DATE,''), '%Y-%m-%d'),

  NULLIF(s.LOCAL_AUTHORITY,''),
  NULLIF(s.CONSTITUENCY,''),
  NULLIF(s.COUNTY,''),

  STR_TO_DATE(NULLIF(s.LODGEMENT_DATE,''), '%Y-%m-%d'),

  NULLIF(s.TRANSACTION_TYPE,''),

  CASE WHEN NULLIF(s.ENVIRONMENT_IMPACT_CURRENT,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.ENVIRONMENT_IMPACT_CURRENT+0.0 ELSE NULL END,
  CASE WHEN NULLIF(s.ENVIRONMENT_IMPACT_POTENTIAL,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.ENVIRONMENT_IMPACT_POTENTIAL+0.0 ELSE NULL END,

  CASE WHEN NULLIF(s.ENERGY_CONSUMPTION_CURRENT,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.ENERGY_CONSUMPTION_CURRENT+0.0 ELSE NULL END,
  CASE WHEN NULLIF(s.ENERGY_CONSUMPTION_POTENTIAL,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.ENERGY_CONSUMPTION_POTENTIAL+0.0 ELSE NULL END,

  CASE WHEN NULLIF(s.CO2_EMISSIONS_CURRENT,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.CO2_EMISSIONS_CURRENT+0.0 ELSE NULL END,
  CASE WHEN NULLIF(s.CO2_EMISS_CURR_PER_FLOOR_AREA,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.CO2_EMISS_CURR_PER_FLOOR_AREA+0.0 ELSE NULL END,
  CASE WHEN NULLIF(s.CO2_EMISSIONS_POTENTIAL,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.CO2_EMISSIONS_POTENTIAL+0.0 ELSE NULL END,

  CASE WHEN NULLIF(s.LIGHTING_COST_CURRENT,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.LIGHTING_COST_CURRENT+0.0 ELSE NULL END,
  CASE WHEN NULLIF(s.LIGHTING_COST_POTENTIAL,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.LIGHTING_COST_POTENTIAL+0.0 ELSE NULL END,

  CASE WHEN NULLIF(s.HEATING_COST_CURRENT,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.HEATING_COST_CURRENT+0.0 ELSE NULL END,
  CASE WHEN NULLIF(s.HEATING_COST_POTENTIAL,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.HEATING_COST_POTENTIAL+0.0 ELSE NULL END,

  CASE WHEN NULLIF(s.HOT_WATER_COST_CURRENT,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.HOT_WATER_COST_CURRENT+0.0 ELSE NULL END,
  CASE WHEN NULLIF(s.HOT_WATER_COST_POTENTIAL,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.HOT_WATER_COST_POTENTIAL+0.0 ELSE NULL END,

  CASE WHEN NULLIF(s.TOTAL_FLOOR_AREA,'') REGEXP '^-?[0-9]+(\\.[0-9]+)?$' THEN s.TOTAL_FLOOR_AREA+0.0 ELSE NULL END,

  NULLIF(s.ENERGY_TARIFF,''),

  NULLIF(s.MAINS_GAS_FLAG,''),

  NULLIF(s.FLOOR_LEVEL,''),

  NULLIF(s.FLAT_TOP_STOREY,''),

  CASE WHEN NULLIF(s.FLAT_STOREY_COUNT,'') REGEXP '^[0-9]+$' THEN s.FLAT_STOREY_COUNT+0 ELSE NULL END,

  NULLIF(s.MAIN_HEATING_CONTROLS,''),

  CASE WHEN NULLIF(s.MULTI_GLAZE_PROPORTION,'') REGEXP '^[0-9]+$' THEN s.MULTI_GLAZE_PROPORTION+0 ELSE NULL END,

  NULLIF(s.GLAZED_TYPE,''),
  NULLIF(s.GLAZED_AREA,''),

  CASE WHEN NULLIF(s.EXTENSION_COUNT,'') REGEXP '^[0-9]+$' THEN s.EXTENSION_COUNT+0 ELSE NULL END,

  CASE WHEN NULLIF(s.NUMBER_HABITABLE_ROOMS,'') REGEXP '^[0-9]+$' THEN s.NUMBER_HABITABLE_ROOMS+0 ELSE NULL END,
  CASE WHEN NULLIF(s.NUMBER_HEATED_ROOMS,'') REGEXP '^[0-9]+$' THEN s.NUMBER_HEATED_ROOMS+0 ELSE NULL END,

  CASE WHEN NULLIF(s.LOW_ENERGY_LIGHTING,'') REGEXP '^[0-9]+$' THEN s.LOW_ENERGY_LIGHTING+0 ELSE NULL END,

  CASE WHEN NULLIF(s.NUMBER_OPEN_FIREPLACES,'') REGEXP '^[0-9]+$' THEN s.NUMBER_OPEN_FIREPLACES+0 ELSE NULL END,

  NULLIF(s.HOTWATER_DESCRIPTION,''),
  NULLIF(s.HOT_WATER_ENERGY_EFF,''),
  NULLIF(s.HOT_WATER_ENV_EFF,''),
  NULLIF(s.FLOOR_DESCRIPTION,''),
  NULLIF(s.FLOOR_ENERGY_EFF,''),
  NULLIF(s.FLOOR_ENV_EFF,''),
  NULLIF(s.WINDOWS_DESCRIPTION,''),
  NULLIF(s.WINDOWS_ENERGY_EFF,''),
  NULLIF(s.WINDOWS_ENV_EFF,''),
  NULLIF(s.WALLS_DESCRIPTION,''),
  NULLIF(s.WALLS_ENERGY_EFF,''),
  NULLIF(s.WALLS_ENV_EFF,''),
  NULLIF(s.SECONDHEAT_DESCRIPTION,''),
  NULLIF(s.SHEATING_ENERGY_EFF,''),
  NULLIF(s.SHEATING_ENV_EFF,''),
  NULLIF(s.ROOF_DESCRIPTION,''),
  NULLIF(s.ROOF_ENERGY_EFF,''),
  NULLIF(s.ROOF_ENV_EFF,''),
  NULLIF(s.MAINHEAT_DESCRIPTION,''),
  NULLIF(s.MAINHEAT_ENERGY_EFF,''),
  NULLIF(s.MAINHEAT_ENV_EFF,''),
  NULLIF(s.MAINHEATCONT_DESCRIPTION,''),
  NULLIF(s.MAINHEATC_ENERGY_EFF,''),
  NULLIF(s.MAINHEATC_ENV_EFF,''),
  NULLIF(s.LIGHTING_DESCRIPTION,''),
  NULLIF(s.LIGHTING_ENERGY_EFF,''),
  NULLIF(s.LIGHTING_ENV_EFF,''),
  NULLIF(s.MAIN_FUEL,''),

  CASE WHEN NULLIF(s.WIND_TURBINE_COUNT,'') REGEXP '^[0-9]+$' THEN s.WIND_TURBINE_COUNT+0 ELSE NULL END,

  NULLIF(s.HEAT_LOSS_CORRIDOR,''),
  NULLIF(s.UNHEATED_CORRIDOR_LENGTH,''),
  NULLIF(s.FLOOR_HEIGHT,''),
  NULLIF(s.PHOTO_SUPPLY,''),
  NULLIF(s.SOLAR_WATER_HEATING_FLAG,''),
  NULLIF(s.MECHANICAL_VENTILATION,''),

  NULLIF(s.ADDRESS,''),
  NULLIF(s.LOCAL_AUTHORITY_LABEL,''),
  NULLIF(s.CONSTITUENCY_LABEL,''),
  NULLIF(s.POSTTOWN,''),
  NULLIF(s.CONSTRUCTION_AGE_BAND,''),

  COALESCE(
    STR_TO_DATE(REPLACE(NULLIF(s.LODGEMENT_DATETIME,''), 'T',' '), '%Y-%m-%d %H:%i:%s'),
    STR_TO_DATE(NULLIF(s.LODGEMENT_DATE,''), '%Y-%m-%d')
  ),

  NULLIF(s.TENURE,''),

  CASE WHEN NULLIF(s.FIXED_LIGHTING_OUTLETS_COUNT,'') REGEXP '^[0-9]+$' THEN s.FIXED_LIGHTING_OUTLETS_COUNT+0 ELSE NULL END,
  CASE WHEN NULLIF(s.LOW_ENERGY_FIXED_LIGHT_COUNT,'') REGEXP '^[0-9]+$' THEN s.LOW_ENERGY_FIXED_LIGHT_COUNT+0 ELSE NULL END,

  CASE WHEN NULLIF(s.UPRN,'') REGEXP '^[0-9]+$' THEN s.UPRN+0 ELSE NULL END,
  NULLIF(s.UPRN_SOURCE,''),

  NULLIF(s.REPORT_TYPE,'')
FROM epc_staging s
WHERE NULLIF(s.LMK_KEY,'') IS NOT NULL
  AND NULLIF(s.LODGEMENT_DATE,'') >= '${Y}-01-01'
  AND NULLIF(s.LODGEMENT_DATE,'') <  '${NEXT_Y}-01-01'
ON DUPLICATE KEY UPDATE
  ADDRESS1 = COALESCE(VALUES(ADDRESS1), epc_certificates.ADDRESS1),
  ADDRESS2 = COALESCE(VALUES(ADDRESS2), epc_certificates.ADDRESS2),
  ADDRESS3 = COALESCE(VALUES(ADDRESS3), epc_certificates.ADDRESS3),
  POSTCODE = COALESCE(VALUES(POSTCODE), epc_certificates.POSTCODE),
  BUILDING_REFERENCE_NUMBER = COALESCE(VALUES(BUILDING_REFERENCE_NUMBER), epc_certificates.BUILDING_REFERENCE_NUMBER),
  CURRENT_ENERGY_RATING = COALESCE(VALUES(CURRENT_ENERGY_RATING), epc_certificates.CURRENT_ENERGY_RATING),
  POTENTIAL_ENERGY_RATING = COALESCE(VALUES(POTENTIAL_ENERGY_RATING), epc_certificates.POTENTIAL_ENERGY_RATING),
  CURRENT_ENERGY_EFFICIENCY = COALESCE(VALUES(CURRENT_ENERGY_EFFICIENCY), epc_certificates.CURRENT_ENERGY_EFFICIENCY),
  POTENTIAL_ENERGY_EFFICIENCY = COALESCE(VALUES(POTENTIAL_ENERGY_EFFICIENCY), epc_certificates.POTENTIAL_ENERGY_EFFICIENCY),
  PROPERTY_TYPE = COALESCE(VALUES(PROPERTY_TYPE), epc_certificates.PROPERTY_TYPE),
  BUILT_FORM = COALESCE(VALUES(BUILT_FORM), epc_certificates.BUILT_FORM),
  INSPECTION_DATE = COALESCE(VALUES(INSPECTION_DATE), epc_certificates.INSPECTION_DATE),
  LOCAL_AUTHORITY = COALESCE(VALUES(LOCAL_AUTHORITY), epc_certificates.LOCAL_AUTHORITY),
  CONSTITUENCY = COALESCE(VALUES(CONSTITUENCY), epc_certificates.CONSTITUENCY),
  COUNTY = COALESCE(VALUES(COUNTY), epc_certificates.COUNTY),
  LODGEMENT_DATE = COALESCE(VALUES(LODGEMENT_DATE), epc_certificates.LODGEMENT_DATE),
  TRANSACTION_TYPE = COALESCE(VALUES(TRANSACTION_TYPE), epc_certificates.TRANSACTION_TYPE),
  ENVIRONMENT_IMPACT_CURRENT = COALESCE(VALUES(ENVIRONMENT_IMPACT_CURRENT), epc_certificates.ENVIRONMENT_IMPACT_CURRENT),
  ENVIRONMENT_IMPACT_POTENTIAL = COALESCE(VALUES(ENVIRONMENT_IMPACT_POTENTIAL), epc_certificates.ENVIRONMENT_IMPACT_POTENTIAL),
  ENERGY_CONSUMPTION_CURRENT = COALESCE(VALUES(ENERGY_CONSUMPTION_CURRENT), epc_certificates.ENERGY_CONSUMPTION_CURRENT),
  ENERGY_CONSUMPTION_POTENTIAL = COALESCE(VALUES(ENERGY_CONSUMPTION_POTENTIAL), epc_certificates.ENERGY_CONSUMPTION_POTENTIAL),
  CO2_EMISSIONS_CURRENT = COALESCE(VALUES(CO2_EMISSIONS_CURRENT), epc_certificates.CO2_EMISSIONS_CURRENT),
  CO2_EMISS_CURR_PER_FLOOR_AREA = COALESCE(VALUES(CO2_EMISS_CURR_PER_FLOOR_AREA), epc_certificates.CO2_EMISS_CURR_PER_FLOOR_AREA),
  CO2_EMISSIONS_POTENTIAL = COALESCE(VALUES(CO2_EMISSIONS_POTENTIAL), epc_certificates.CO2_EMISSIONS_POTENTIAL),
  LIGHTING_COST_CURRENT = COALESCE(VALUES(LIGHTING_COST_CURRENT), epc_certificates.LIGHTING_COST_CURRENT),
  LIGHTING_COST_POTENTIAL = COALESCE(VALUES(LIGHTING_COST_POTENTIAL), epc_certificates.LIGHTING_COST_POTENTIAL),
  HEATING_COST_CURRENT = COALESCE(VALUES(HEATING_COST_CURRENT), epc_certificates.HEATING_COST_CURRENT),
  HEATING_COST_POTENTIAL = COALESCE(VALUES(HEATING_COST_POTENTIAL), epc_certificates.HEATING_COST_POTENTIAL),
  HOT_WATER_COST_CURRENT = COALESCE(VALUES(HOT_WATER_COST_CURRENT), epc_certificates.HOT_WATER_COST_CURRENT),
  HOT_WATER_COST_POTENTIAL = COALESCE(VALUES(HOT_WATER_COST_POTENTIAL), epc_certificates.HOT_WATER_COST_POTENTIAL),
  TOTAL_FLOOR_AREA = COALESCE(VALUES(TOTAL_FLOOR_AREA), epc_certificates.TOTAL_FLOOR_AREA),
  ENERGY_TARIFF = COALESCE(VALUES(ENERGY_TARIFF), epc_certificates.ENERGY_TARIFF),
  MAINS_GAS_FLAG = COALESCE(VALUES(MAINS_GAS_FLAG), epc_certificates.MAINS_GAS_FLAG),
  FLOOR_LEVEL = COALESCE(VALUES(FLOOR_LEVEL), epc_certificates.FLOOR_LEVEL),
  FLAT_TOP_STOREY = COALESCE(VALUES(FLAT_TOP_STOREY), epc_certificates.FLAT_TOP_STOREY),
  FLAT_STOREY_COUNT = COALESCE(VALUES(FLAT_STOREY_COUNT), epc_certificates.FLAT_STOREY_COUNT),
  MAIN_HEATING_CONTROLS = COALESCE(VALUES(MAIN_HEATING_CONTROLS), epc_certificates.MAIN_HEATING_CONTROLS),
  MULTI_GLAZE_PROPORTION = COALESCE(VALUES(MULTI_GLAZE_PROPORTION), epc_certificates.MULTI_GLAZE_PROPORTION),
  GLAZED_TYPE = COALESCE(VALUES(GLAZED_TYPE), epc_certificates.GLAZED_TYPE),
  GLAZED_AREA = COALESCE(VALUES(GLAZED_AREA), epc_certificates.GLAZED_AREA),
  EXTENSION_COUNT = COALESCE(VALUES(EXTENSION_COUNT), epc_certificates.EXTENSION_COUNT),
  NUMBER_HABITABLE_ROOMS = COALESCE(VALUES(NUMBER_HABITABLE_ROOMS), epc_certificates.NUMBER_HABITABLE_ROOMS),
  NUMBER_HEATED_ROOMS = COALESCE(VALUES(NUMBER_HEATED_ROOMS), epc_certificates.NUMBER_HEATED_ROOMS),
  LOW_ENERGY_LIGHTING = COALESCE(VALUES(LOW_ENERGY_LIGHTING), epc_certificates.LOW_ENERGY_LIGHTING),
  NUMBER_OPEN_FIREPLACES = COALESCE(VALUES(NUMBER_OPEN_FIREPLACES), epc_certificates.NUMBER_OPEN_FIREPLACES),
  HOTWATER_DESCRIPTION = COALESCE(VALUES(HOTWATER_DESCRIPTION), epc_certificates.HOTWATER_DESCRIPTION),
  HOT_WATER_ENERGY_EFF = COALESCE(VALUES(HOT_WATER_ENERGY_EFF), epc_certificates.HOT_WATER_ENERGY_EFF),
  HOT_WATER_ENV_EFF = COALESCE(VALUES(HOT_WATER_ENV_EFF), epc_certificates.HOT_WATER_ENV_EFF),
  FLOOR_DESCRIPTION = COALESCE(VALUES(FLOOR_DESCRIPTION), epc_certificates.FLOOR_DESCRIPTION),
  FLOOR_ENERGY_EFF = COALESCE(VALUES(FLOOR_ENERGY_EFF), epc_certificates.FLOOR_ENERGY_EFF),
  FLOOR_ENV_EFF = COALESCE(VALUES(FLOOR_ENV_EFF), epc_certificates.FLOOR_ENV_EFF),
  WINDOWS_DESCRIPTION = COALESCE(VALUES(WINDOWS_DESCRIPTION), epc_certificates.WINDOWS_DESCRIPTION),
  WINDOWS_ENERGY_EFF = COALESCE(VALUES(WINDOWS_ENERGY_EFF), epc_certificates.WINDOWS_ENERGY_EFF),
  WINDOWS_ENV_EFF = COALESCE(VALUES(WINDOWS_ENV_EFF), epc_certificates.WINDOWS_ENV_EFF),
  WALLS_DESCRIPTION = COALESCE(VALUES(WALLS_DESCRIPTION), epc_certificates.WALLS_DESCRIPTION),
  WALLS_ENERGY_EFF = COALESCE(VALUES(WALLS_ENERGY_EFF), epc_certificates.WALLS_ENERGY_EFF),
  WALLS_ENV_EFF = COALESCE(VALUES(WALLS_ENV_EFF), epc_certificates.WALLS_ENV_EFF),
  SECONDHEAT_DESCRIPTION = COALESCE(VALUES(SECONDHEAT_DESCRIPTION), epc_certificates.SECONDHEAT_DESCRIPTION),
  SHEATING_ENERGY_EFF = COALESCE(VALUES(SHEATING_ENERGY_EFF), epc_certificates.SHEATING_ENERGY_EFF),
  SHEATING_ENV_EFF = COALESCE(VALUES(SHEATING_ENV_EFF), epc_certificates.SHEATING_ENV_EFF),
  ROOF_DESCRIPTION = COALESCE(VALUES(ROOF_DESCRIPTION), epc_certificates.ROOF_DESCRIPTION),
  ROOF_ENERGY_EFF = COALESCE(VALUES(ROOF_ENERGY_EFF), epc_certificates.ROOF_ENERGY_EFF),
  ROOF_ENV_EFF = COALESCE(VALUES(ROOF_ENV_EFF), epc_certificates.ROOF_ENV_EFF),
  MAINHEAT_DESCRIPTION = COALESCE(VALUES(MAINHEAT_DESCRIPTION), epc_certificates.MAINHEAT_DESCRIPTION),
  MAINHEAT_ENERGY_EFF = COALESCE(VALUES(MAINHEAT_ENERGY_EFF), epc_certificates.MAINHEAT_ENERGY_EFF),
  MAINHEAT_ENV_EFF = COALESCE(VALUES(MAINHEAT_ENV_EFF), epc_certificates.MAINHEAT_ENV_EFF),
  MAINHEATCONT_DESCRIPTION = COALESCE(VALUES(MAINHEATCONT_DESCRIPTION), epc_certificates.MAINHEATCONT_DESCRIPTION),
  MAINHEATC_ENERGY_EFF = COALESCE(VALUES(MAINHEATC_ENERGY_EFF), epc_certificates.MAINHEATC_ENERGY_EFF),
  MAINHEATC_ENV_EFF = COALESCE(VALUES(MAINHEATC_ENV_EFF), epc_certificates.MAINHEATC_ENV_EFF),
  LIGHTING_DESCRIPTION = COALESCE(VALUES(LIGHTING_DESCRIPTION), epc_certificates.LIGHTING_DESCRIPTION),
  LIGHTING_ENERGY_EFF = COALESCE(VALUES(LIGHTING_ENERGY_EFF), epc_certificates.LIGHTING_ENERGY_EFF),
  LIGHTING_ENV_EFF = COALESCE(VALUES(LIGHTING_ENV_EFF), epc_certificates.LIGHTING_ENV_EFF),
  MAIN_FUEL = COALESCE(VALUES(MAIN_FUEL), epc_certificates.MAIN_FUEL),
  WIND_TURBINE_COUNT = COALESCE(VALUES(WIND_TURBINE_COUNT), epc_certificates.WIND_TURBINE_COUNT),
  HEAT_LOSS_CORRIDOR = COALESCE(VALUES(HEAT_LOSS_CORRIDOR), epc_certificates.HEAT_LOSS_CORRIDOR),
  UNHEATED_CORRIDOR_LENGTH = COALESCE(VALUES(UNHEATED_CORRIDOR_LENGTH), epc_certificates.UNHEATED_CORRIDOR_LENGTH),
  FLOOR_HEIGHT = COALESCE(VALUES(FLOOR_HEIGHT), epc_certificates.FLOOR_HEIGHT),
  PHOTO_SUPPLY = COALESCE(VALUES(PHOTO_SUPPLY), epc_certificates.PHOTO_SUPPLY),
  SOLAR_WATER_HEATING_FLAG = COALESCE(VALUES(SOLAR_WATER_HEATING_FLAG), epc_certificates.SOLAR_WATER_HEATING_FLAG),
  MECHANICAL_VENTILATION = COALESCE(VALUES(MECHANICAL_VENTILATION), epc_certificates.MECHANICAL_VENTILATION),
  ADDRESS = COALESCE(VALUES(ADDRESS), epc_certificates.ADDRESS),
  LOCAL_AUTHORITY_LABEL = COALESCE(VALUES(LOCAL_AUTHORITY_LABEL), epc_certificates.LOCAL_AUTHORITY_LABEL),
  CONSTITUENCY_LABEL = COALESCE(VALUES(CONSTITUENCY_LABEL), epc_certificates.CONSTITUENCY_LABEL),
  POSTTOWN = COALESCE(VALUES(POSTTOWN), epc_certificates.POSTTOWN),
  CONSTRUCTION_AGE_BAND = COALESCE(VALUES(CONSTRUCTION_AGE_BAND), epc_certificates.CONSTRUCTION_AGE_BAND),
  LODGEMENT_DATETIME = COALESCE(VALUES(LODGEMENT_DATETIME), epc_certificates.LODGEMENT_DATETIME),
  TENURE = COALESCE(VALUES(TENURE), epc_certificates.TENURE),
  FIXED_LIGHTING_OUTLETS_COUNT = COALESCE(VALUES(FIXED_LIGHTING_OUTLETS_COUNT), epc_certificates.FIXED_LIGHTING_OUTLETS_COUNT),
  LOW_ENERGY_FIXED_LIGHT_COUNT = COALESCE(VALUES(LOW_ENERGY_FIXED_LIGHT_COUNT), epc_certificates.LOW_ENERGY_FIXED_LIGHT_COUNT),
  UPRN = COALESCE(VALUES(UPRN), epc_certificates.UPRN),
  UPRN_SOURCE = COALESCE(VALUES(UPRN_SOURCE), epc_certificates.UPRN_SOURCE),
  REPORT_TYPE = COALESCE(VALUES(REPORT_TYPE), epc_certificates.REPORT_TYPE);
SQL

  echo ">>> Year ${Y} complete."
done

echo ">>> Done."
