#!/usr/bin/env bash
set -euo pipefail

# ===== CONFIG =====
DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_USER="root"
DB_NAME="uk_property"

# Folder containing the quarterly CSVs
CSV_DIR="/Users/wisenerl/Downloads/scotland"

# If your files are Windows line endings, change to: $'\r\n'
LINE_ENDING=$'\n'

shopt -s nullglob

files=( "${CSV_DIR}"/*.csv )
if [ ${#files[@]} -eq 0 ]; then
  echo "No .csv files found in: ${CSV_DIR}"
  exit 1
fi

echo "Found ${#files[@]} CSV files in ${CSV_DIR}"
echo "Importing into epc_certificates_scotland (assumes table already TRUNCATED)."

# Optional: show connection info
echo "Using: mysql --local-infile=1 -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USER} ${DB_NAME}"

# Loop files in a stable order
IFS=$'\n' sorted=( $(printf '%s\n' "${files[@]}" | sort) )
unset IFS

for f in "${sorted[@]}"; do
  base="$(basename "$f")"
  echo ">>> Importing ${base}"

  mysql --local-infile=1 -h "${DB_HOST}" -P "${DB_PORT}" -u "${DB_USER}" "${DB_NAME}" <<SQL
LOAD DATA LOCAL INFILE '${f}'
INTO TABLE epc_certificates_scotland
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '${LINE_ENDING}'
IGNORE 1 LINES
(
BUILDING_REFERENCE_NUMBER,OSG_REFERENCE_NUMBER,ADDRESS1,ADDRESS2,ADDRESS3,POSTCODE,INSPECTION_DATE,TYPE_OF_ASSESSMENT,
LODGEMENT_DATE,ENERGY_CONSUMPTION_CURRENT,TOTAL_FLOOR_AREA,\`3_YR_ENERGY_COST_CURRENT\`,\`3_YR_ENERGY_SAVINGS_POTENTIAL\`,
CURRENT_ENERGY_EFFICIENCY,CURRENT_ENERGY_RATING,POTENTIAL_ENERGY_EFFICIENCY,POTENTIAL_ENERGY_RATING,
ENVIRONMENT_IMPACT_CURRENT,CURRENT_ENVIRONMENTAL_RATING,ENVIRONMENT_IMPACT_POTENTIAL,POTENTIAL_ENVIRONMENTAL_RATING,
CO2_EMISS_CURR_PER_FLOOR_AREA,IMPROVEMENTS,WALL_DESCRIPTION,WALL_ENERGY_EFF,WALL_ENV_EFF,ROOF_DESCRIPTION,ROOF_ENERGY_EFF,
ROOF_ENV_EFF,FLOOR_DESCRIPTION,FLOOR_ENERGY_EFF,FLOOR_ENV_EFF,WINDOWS_DESCRIPTION,WINDOWS_ENERGY_EFF,WINDOWS_ENV_EFF,
MAINHEAT_DESCRIPTION,MAINHEAT_ENERGY_EFF,MAINHEAT_ENV_EFF,MAINHEATCONT_DESCRIPTION,MAINHEATC_ENERGY_EFF,MAINHEATC_ENV_EFF,
SECONDHEAT_DESCRIPTION,SHEATING_ENERGY_EFF,SHEATING_ENV_EFF,HOTWATER_DESCRIPTION,HOT_WATER_ENERGY_EFF,HOT_WATER_ENV_EFF,
LIGHTING_DESCRIPTION,LIGHTING_ENERGY_EFF,LIGHTING_ENV_EFF,AIR_TIGHTNESS_DESCRIPTION,AIR_TIGHTNESS_ENERGY_EFF,
AIR_TIGHTNESS_ENV_EFF,CO2_EMISSIONS_CURRENT,CO2_EMISSIONS_POTENTIAL,HEATING_COST_CURRENT,HEATING_COST_POTENTIAL,
HOT_WATER_COST_CURRENT,HOT_WATER_COST_POTENTIAL,LIGHTING_COST_CURRENT,LIGHTING_COST_POTENTIAL,ALTERNATIVE_IMPROVEMENTS,
LZC_ENERGY_SOURCES,SPACE_HEATING_DEMAND,WATER_HEATING_DEMAND,IMPACT_LOFT_INSULATION,IMPACT_CAVITY_WALL_INSULATION,
IMPACT_SOLID_WALL_INSULATION,ADDENDUM_TEXT,CONSTRUCTION_AGE_BAND,FLOOR_HEIGHT,DATA_ZONE,ENERGY_CONSUMPTION_POTENTIAL,
EXTENSION_COUNT,FIXED_LIGHTING_OUTLETS_COUNT,LOW_ENERGY_FIXED_LIGHT_COUNT,LOW_ENERGY_LIGHTING,FLOOR_LEVEL,FLAT_TOP_STOREY,
GLAZED_AREA,NUMBER_HABITABLE_ROOMS,HEAT_LOSS_CORRIDOOR,NUMBER_HEATED_ROOMS,LOCAL_AUTHORITY_LABEL,MAINS_GAS_FLAG,
MAIN_HEATING_CATEGORY,MAIN_FUEL,MAIN_HEATING_CONTROLS,MECHANICAL_VENTILATION,ENERGY_TARIFF,MULTI_GLAZE_PROPORTION,
GLAZED_TYPE,NUMBER_OPEN_FIREPLACES,PHOTO_SUPPLY,SOLAR_WATER_HEATING_FLAG,TENURE,TRANSACTION_TYPE,UNHEATED_CORRIDOR_LENGTH,
CONSTITUENCY,CONSTITUENCY_LABEL,WIND_TURBINE_COUNT,BUILT_FORM,PROPERTY_TYPE,DATA_ZONE_2011,CREATED_AT,REPORT_REFERENCE_NUMBER
)
SET source_file = '${base}';
SQL
done

echo ">>> Done. Summary by source_file:"
mysql -h "${DB_HOST}" -P "${DB_PORT}" -u "${DB_USER}" "${DB_NAME}" -e "
SELECT source_file, COUNT(*) AS rows
FROM epc_certificates_scotland
GROUP BY source_file
ORDER BY source_file;
"
