@extends('layouts.app')

@section('title', 'Deprivation details: '.$row->LSOA_Name_2021)

@section('content')
<div class="max-w-7xl mx-auto p-6 space-y-8">

  {{-- Header card --}}
  <section class="relative overflow-hidden rounded border border-gray-200 bg-white/80 p-6 md:p-8 shadow-sm">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
      <div class="max-w-3xl">
        <h1 class="text-2xl md:text-3xl font-semibold tracking-tight text-gray-900 mb-2">English Index of Multiple Deprivation</h1>
        <div class="mt-1">
          <span class="inline-flex items-center rounded-full bg-zinc-200 text-zinc-700 text-xs px-2 py-1 ring-1 ring-inset ring-zinc-200 mb-2">Dataset: IMD 2025</span>
        </div>
        <p class="mt-1 text-sm text-gray-600">
          LSOA21: <span class="">{{ $row->LSOA_Code_2021 }}</span> ·  {{ $row->LSOA_Name_2021 }}
        </p>
        <p class="mt-2 text-xs text-gray-600">
          Note: Lower rank/decile = more deprived; higher rank/decile = less deprived. IMD 2025 (England).  Next update not expected until 2031.
        </p>
        <p class="text-xs text-zinc-600 mt-4">
          Decile colours: <span class="inline-block align-middle rounded px-1.5 py-0.5 text-[11px] bg-rose-300 text-zinc-900">1–3</span> higher deprivation ·
          <span class="inline-block align-middle rounded px-1.5 py-0.5 text-[11px] bg-orange-300 text-zinc-900">4–7</span> mid ·
          <span class="inline-block align-middle rounded px-1.5 py-0.5 text-[11px] bg-emerald-300 text-zinc-900">8–10</span> lower deprivation.
        </p>
      </div>
      <div class="mt-2 md:mt-0 md:ml-8 flex-shrink-0">
        <img
          src="{{ asset('assets/images/site/deprivation.jpg') }}"
          alt="Deprivation illustration"
          class="h-24 md:h-40 w-auto opacity-90"
        >
      </div>
    </div>
  </section>

  @if($row->LAT && $row->LONG)
    <section class="rounded border border-gray-200 bg-white/80 p-4 md:p-6 shadow-sm">
      <h2 class="text-lg font-semibold text-gray-900">Location Map</h2>
      <p class="text-xs text-zinc-500 mb-3">The shaded area on the map below shows the area that relates to the data for this area.</p>

      {{-- Leaflet CSS --}}
      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" crossorigin="" />
      <style>
        /* Ensure Leaflet tiles aren't resized by global img styles and container has proper layout */
        #lsoa-map { height: 28rem; position: relative; }
        .leaflet-container { height: 100%; width: 100%; position: relative; }
        .leaflet-container img { max-width: none !important; }
      </style>

      <div id="lsoa-map" class="w-full rounded border"></div>

      {{-- Leaflet JS --}}
      <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" crossorigin=""></script>

      <script>
  (function(){
    var lat  = {{ $row->LAT ?? 'null' }};
    var lon  = {{ $row->LONG ?? 'null' }};
    var code = @json($row->LSOA_Code_2021); // e.g. "E01000001"

    if (lat === null || lon === null) {
      return; // no map data available
    }

    // create leaflet map
    var map = L.map('lsoa-map', { scrollWheelZoom: false }).setView([lat, lon], 13);

    // Default base layer (OpenStreetMap)
    var osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
      attribution: '&copy; OpenStreetMap contributors'
    }).addTo(map);

    // Satellite layers (Esri imagery + labels)
    var satellite = L.tileLayer(
      'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
      {
        maxZoom: 19,
        attribution: 'Tiles © Esri'
      }
    );

    var labels = L.tileLayer(
      'https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',
      {
        maxZoom: 19,
        attribution: 'Labels © Esri'
      }
    );

    // Layer control button to switch map type
    var baseMaps = {
      'Standard Map': osm,
      'Satellite View': L.layerGroup([satellite, labels])
    };

    L.control.layers(baseMaps, null, { position: 'topright', collapsed: false }).addTo(map);

    // add marker so we can bring it to front later
    var marker = L.marker([lat, lon])
      .addTo(map)
      .bindPopup(@json($row->LSOA_Name_2021));

    // try to load the sliced polygon for this LSOA
    // these files were generated by geo:slice-lsoa into public/geo/lsoa/sliced/{LSOA}.geojson
    var boundaryUrl = '/geo/lsoa/sliced/' + code + '.geojson';

    fetch(boundaryUrl)
      .then(function(resp){
        if (!resp.ok) throw new Error('No boundary file for ' + code);
        return resp.json();
      })
      .then(function(geojsonData){
        var boundaryLayer = L.geoJSON(geojsonData, {
          style: function () {
            return {
              color: '#2563eb',        // blue border for clarity
              weight: 3,               // slightly thicker border
              opacity: 1,
              fillColor: 'rgba(37,99,235,0.15)', // translucent blue fill
              fillOpacity: 0.7
            };
          }
        }).addTo(map);

        // zoom map to polygon; fallback to point if something odd happens
        try {
          map.fitBounds(boundaryLayer.getBounds(), { padding: [20,20] });
          marker.bringToFront();
          map.setZoom(13); // force starting zoom level
        } catch (e) {
          map.setView([lat, lon], 13);
        }
      })
      .catch(function(err){
        // If we don't have a polygon (e.g. Scotland/Wales or missing slice), we just leave the marker view.
        // console.warn(err);
      });
  })();
</script>
    </section>
  @endif

  {{-- Domain breakdown --}}
  <section class="rounded border border-gray-200 bg-white/80 p-6 shadow-sm">
    <h2 class="text-lg font-semibold text-gray-900 mb-4">Domain Breakdown for {{ $row->LSOA_Name_2021 }}</h2>

    @php
      // Helper for badge colour based on decile: background/text colour by decile range, border always gray-200
      $decileBadge = function ($decile) {
          if (is_null($decile)) {
              return ['bg' => 'bg-gray-100', 'text' => 'text-zinc-900', 'border' => 'border-zinc-50'];
          }

          // normalise e.g. "6 ", "05" etc
          $decile = (int) trim((string) $decile);

          if ($decile >= 1 && $decile <= 3) {
              return ['bg' => 'bg-rose-200', 'text' => 'text-zinc-900', 'border' => 'border-gray-200'];
          }
          if ($decile >= 4 && $decile <= 6) {
              return ['bg' => 'bg-amber-200', 'text' => 'text-zinc-900', 'border' => 'border-gray-200'];
          }
          if ($decile >= 7 && $decile <= 10) {
              return ['bg' => 'bg-green-200', 'text' => 'text-zinc-900', 'border' => 'border-gray-200'];
          }

          return ['bg' => 'bg-gray-100', 'text' => 'text-zinc-900', 'border' => 'border-gray-200'];
      };

      $overallDecileStyles = $decileBadge($overall['decile'] ?? null);
    @endphp

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      {{-- Overall IMD card --}}
      <div class="rounded border border-gray-200 bg-white/80 p-4 shadow-sm">
        <div class="flex items-start justify-between">
          <div class="font-medium text-gray-900">Overall IMD</div>
          <div class="text-xs text-gray-500">&nbsp;</div>
        </div>
        <div class="mt-3 flex flex-wrap items-center gap-4 text-sm text-gray-700">
          <span class="inline-flex items-center gap-1 rounded px-2 py-1 border text-xs font-medium {{ $overallDecileStyles['bg'] }} {{ $overallDecileStyles['text'] }} {{ $overallDecileStyles['border'] }}">
            <span>Decile:</span>
            <span class="font-semibold">{{ $overall['decile'] ?? 'N/A' }}</span>
          </span>
          <span class="text-sm text-gray-700">
            Rank: {{ isset($overall['rank']) ? number_format($overall['rank']) . ' out of ' . number_format($total) : 'N/A' }}
          </span>
        </div>
        <p class="text-xs mt-4 text-gray-500">Overall score combining the individual domain scores.</p>
      </div>

      @foreach($domains as $d)
        @php
          $styles = $decileBadge($d['decile'] ?? null);
        @endphp
        <div class="rounded border border-gray-200 bg-white/80 p-4 shadow-sm">
          <div class="flex items-start justify-between">
            <div class="font-medium text-gray-900">{{ $d['label'] }}</div>
            <div class="text-xs text-gray-500">{{ $d['weight'] ?? '' }} weight</div>
          </div>
          <div class="mt-3 flex flex-wrap items-center gap-4 text-sm text-gray-700">
            <span class="inline-flex items-center gap-1 rounded px-2 py-1 border text-xs font-medium {{ $styles['bg'] }} {{ $styles['text'] }} {{ $styles['border'] }}">
              <span>Decile:</span>
              <span class="font-semibold">{{ $d['decile'] ?? 'N/A' }}</span>
            </span>
            <span class="text-sm text-gray-700">
              Rank: {{ isset($d['rank']) ? number_format($d['rank']) . ' out of ' . number_format($total) : 'N/A' }}
            </span>
          </div>
          <p class="mt-3 text-xs text-gray-500 leading-snug">
              @switch($d['label'])
                  @case('Income')
                      Measures deprivation due to low income, including people receiving income‑related benefits and tax credits.
                      @break

                  @case('Employment')
                      Captures involuntary exclusion from the labour market, such as unemployment, long‑term sickness, disability, or caring responsibilities.
                      @break

                  @case('Education, Skills & Training')
                      Reflects educational attainment and skills in children and adults, including school results, qualifications, and access to higher education.
                      @break

                  @case('Health Deprivation & Disability')
                      Indicates risk of premature death and reduced quality of life due to illness, disability, or mental health conditions.
                      @break

                  @case('Crime')
                      Measures risk of personal and material victimisation, including violence, burglary, theft, and criminal damage.
                      @break

                  @case('Barriers to Housing & Services')
                      Assesses access to suitable housing and essential services, including affordability, overcrowding, and distance to key services.
                      @break

                  @case('Living Environment')
                      Covers quality of the local environment, including housing condition, air quality, pollution, and road traffic incidents.
                      @break

                  @default
                      Part of the overall deprivation score.
              @endswitch
          </p>
        </div>
      @endforeach
    </div>
  </section>

</div>
@endsection