<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RentalCost extends Model
{
    protected $table = 'rental_costs';

    protected $fillable = [
        'time_period',
        'area_code',
        'area_name',
        'region_or_country_name',
        'index',
        'monthly_change',
        'annual_change',
        'rental_price',
        'index_one_bed',
        'monthly_change_one_bed',
        'annual_change_one_bed',
        'rental_price_one_bed',
        'index_two_bed',
        'monthly_change_two_bed',
        'annual_change_two_bed',
        'rental_price_two_bed',
        'index_three_bed',
        'monthly_change_three_bed',
        'annual_change_three_bed',
        'rental_price_three_bed',
        'index_four_or_more_bed',
        'monthly_change_four_or_more_bed',
        'annual_change_four_or_more_bed',
        'rental_price_four_or_more_bed',
        'index_detached',
        'monthly_change_detached',
        'annual_change_detached',
        'rental_price_detached',
        'index_semidetached',
        'monthly_change_semidetached',
        'annual_change_semidetached',
        'rental_price_semidetached',
        'index_terraced',
        'monthly_change_terraced',
        'annual_change_terraced',
        'rental_price_terraced',
        'index_flat_maisonette',
        'monthly_change_flat_maisonette',
        'annual_change_flat_maisonette',
        'rental_price_flat_maisonette',
    ];

    protected $casts = [
        'index' => 'float',
        'monthly_change' => 'float',
        'annual_change' => 'float',
        'rental_price' => 'float',
        'index_one_bed' => 'float',
        'monthly_change_one_bed' => 'float',
        'annual_change_one_bed' => 'float',
        'rental_price_one_bed' => 'float',
        'index_two_bed' => 'float',
        'monthly_change_two_bed' => 'float',
        'annual_change_two_bed' => 'float',
        'rental_price_two_bed' => 'float',
        'index_three_bed' => 'float',
        'monthly_change_three_bed' => 'float',
        'annual_change_three_bed' => 'float',
        'rental_price_three_bed' => 'float',
        'index_four_or_more_bed' => 'float',
        'monthly_change_four_or_more_bed' => 'float',
        'annual_change_four_or_more_bed' => 'float',
        'rental_price_four_or_more_bed' => 'float',
        'index_detached' => 'float',
        'monthly_change_detached' => 'float',
        'annual_change_detached' => 'float',
        'rental_price_detached' => 'float',
        'index_semidetached' => 'float',
        'monthly_change_semidetached' => 'float',
        'annual_change_semidetached' => 'float',
        'rental_price_semidetached' => 'float',
        'index_terraced' => 'float',
        'monthly_change_terraced' => 'float',
        'annual_change_terraced' => 'float',
        'rental_price_terraced' => 'float',
        'index_flat_maisonette' => 'float',
        'monthly_change_flat_maisonette' => 'float',
        'annual_change_flat_maisonette' => 'float',
        'rental_price_flat_maisonette' => 'float',
    ];
}
